import { Server, ServerInfo, User } from "../src/db/dbtypes";
import dotenv from "dotenv";
dotenv.config();

const defaultPassword = process.env.DEFAULT;

const computers: Server[] = [
    {
        ipaddress: "192.168.15.11",
        Name: "Ubuntu 24",
        "OS Type": "linux",
        domain: "",
        password_changes: 0,
        users: [
            {
                domain: "",
                failedPasswords: [],
                hostname: "Ubuntu 24",
                ipaddress: "192.168.15.11",
                password: defaultPassword || "Password123",
                password_changes: 0,
                ssh_key: false,
                user_id: "ubuntu24",
                username: "root",
                oldPasswords: [],
            },
        ],
    },
    {
        ipaddress: "192.168.15.12",
        Name: "Centos 8",
        "OS Type": "linux",
        domain: "",
        password_changes: 0,
        users: [
            {
                domain: "",
                failedPasswords: [],
                hostname: "Centos 8",
                ipaddress: "192.168.15.12",
                password: defaultPassword || "Password123",
                password_changes: 0,
                ssh_key: false,
                user_id: "Centos8",
                username: "root",
                oldPasswords: [],
            },
        ],
    },
    {
        ipaddress: "192.168.15.13",
        Name: "Centos 7",
        "OS Type": "linux",
        domain: "",
        password_changes: 0,
        users: [
            {
                domain: "",
                failedPasswords: [],
                hostname: "Centos 7",
                ipaddress: "192.168.15.13",
                password: defaultPassword || "Password123",
                password_changes: 0,
                ssh_key: false,
                user_id: "Centos7",
                username: "root",
                oldPasswords: [],
            },
        ],
    },
    {
        ipaddress: "192.168.15.14",
        Name: "Freebsd 13",
        "OS Type": "freebsd",
        domain: "",
        password_changes: 0,
        users: [
            {
                domain: "",
                failedPasswords: [],
                hostname: "Freebsd 13",
                ipaddress: "192.168.15.14",
                password: defaultPassword || "Password123",
                password_changes: 0,
                ssh_key: false,
                user_id: "Freebsd 13",
                username: "root",
                oldPasswords: [],
            },
        ],
    },
    {
        ipaddress: "192.168.15.15",
        Name: "Opensuse 15.4",
        "OS Type": "linux",
        domain: "",
        password_changes: 0,
        users: [
            {
                domain: "",
                failedPasswords: [],
                hostname: "Opensuse 15.4",
                ipaddress: "192.168.15.15",
                password: defaultPassword || "Password123",
                password_changes: 0,
                ssh_key: false,
                user_id: "Opensuse 15.4",
                username: "root",
                oldPasswords: [],
            },
        ],
    },
    {
        ipaddress: "192.168.15.16",
        Name: "Ubuntu 18",
        "OS Type": "linux",
        domain: "",
        password_changes: 0,
        users: [
            {
                domain: "",
                failedPasswords: [],
                hostname: "Ubuntu 18",
                ipaddress: "192.168.15.16",
                password: defaultPassword || "Password123",
                password_changes: 0,
                ssh_key: false,
                user_id: "Ubuntu 15.4",
                username: "root",
                oldPasswords: [],
            },
        ],
    },
    {
        ipaddress: "192.168.15.17",
        Name: "Alpine 3.13",
        "OS Type": "linux",
        domain: "",
        password_changes: 0,
        users: [
            {
                domain: "",
                failedPasswords: [],
                hostname: "Alpine 3.13",
                ipaddress: "192.168.15.17",
                password: defaultPassword || "Password123",
                password_changes: 0,
                ssh_key: false,
                user_id: "Alpine 3.13",
                username: "root",
                oldPasswords: [],
            },
        ],
    },
    {
        ipaddress: "192.168.15.18",
        Name: "Windows Server 2022",
        "OS Type": "windows",
        domain: "",
        password_changes: 0,
        users: [
            {
                domain: "",
                failedPasswords: [],
                hostname: "Windows Server 2022",
                ipaddress: "192.168.15.18",
                password: defaultPassword || "Password123",
                password_changes: 0,
                ssh_key: false,
                user_id: "Windows Server 2022",
                username: "Administrator",
                oldPasswords: [],
            },
        ],
    },
];

export { computers };
